### ISSUE TITLE
Doesn't seem to work with browser extensions.

### ISSUE THREAD

**Issue by MicahZoltu** [guybedford/es-module-shims#291]
I have a simple browser extension with the following content security policy in the manifest:
```json
"content_security_policy": "script-src 'self' blob: 'unsafe-eval'; object-src 'self';",
```
Unfortunately, in Brave (Chromium) I get the following error:
```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-KpErCcKFw1JO43PPdJr9haK1HgAR/Fri2ZDn0RRaS8E='), or a nonce ('nonce-...') is required to enable inline execution.
```
The suggested workarounds (nonce and unsafe-inline) don't actually work because both of those policies are disabled in Chromium extensions.  Adding them results in them getting stripped and the same error presented.

Meanwhile, over in Firefox, I can't seem to get the initial module to load at all.  When I run in polyfill mode I get the expected
```
Uncaught TypeError: Error resolving module specifier “@zoltu/ethereum-browser-sdk”. Relative module specifiers must start with “./”, “../” or “/”.
```
but I don't get the following line saying "safe to ignore" and nothing appears to load.  If I run in shim mode, I don't get that error but I don't see any indication that the `module-shim` script is loading/executing at all.

----

It is worth noting that this same plugin *used* to work in firefox and chrome (~2.5 years ago).  The project was shelved and I just updated es-module-shim but the problem also could be related to a change in Firefox/Chromium's CSPs.

**Comment by MicahZoltu** [comment]
I just rolled back to es-module-shims 0.6.0 and everything is working again (using shim mode, since polyfill mode didn't exist back then), suggesting that something changed between then and now to break this package working in a browser extension (or perhaps I need to do something additional to make it work now).

**Comment by guybedford** [comment]
Thanks @MicahZoltu agreed this should work, especially if it did before.

Can you try using the Wasm build at https://unpkg.com/browse/es-module-shims@1.5.4/dist/es-module-shims.wasm.js instead of the CSP-compatible build? The CSP build injects inline scripts instead of using eval which is likely the issue here.

**Comment by MicahZoltu** [comment]
I tested with `.wasm.js` and experienced the same issue.  Note: All I did was update 0.6.0 (working) to 1.5.4 and changed the following:
```html
<script type='module' src='./vendor/es-module-shims/es-module-shims.js'></script>
```
to
```html
<script type='module' src='./vendor/es-module-shims/es-module-shims.wasm.js'></script>
```
Let me know if my test should do more than that.

**Comment by guybedford** [comment]
@MicahZoltu yes that's all that you need. Appreciated for the update.

There is only one other script injection that is done by es module shims and that is via an iframe to detect support for import maps. I've just released 1.5.5 with a fix here to use the new `HTMLScriptElement.supports('importmap')` API instead which should then result in the Wasm build doing no script injections at all. Please try this new version if you can and let me know how it goes.

**Comment by MicahZoltu** [comment]
That appears to have fixed the problem, thanks!

Fixed in #292.

**Comment by MicahZoltu** [comment]
This seems to have returned.  😢  Brave: Version 1.39.122  Chromium: 102.0.5005.115 (Official Build)  (64-bit)

Error:
> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-KpErCcKFw1JO43PPdJr9haK1HgAR/Fri2ZDn0RRaS8E='), or a nonce ('nonce-...') is required to enable inline execution.

Error line points to the `<script type='importmap'>` line in `backeground.html`.

manifest.json
```json
{
	"manifest_version": 2,
	"name": "My Plugin",
	"version": "1.0",
	"description": "Description",
	"permissions": [ "activeTab" ],
	// eval is used by es-module-shims, thus we need to enable it. as a development policy, it should never be used in the background script
	"content_security_policy": "script-src 'self' blob: 'unsafe-eval'; object-src 'self';",
	"browser_action": {
		"default_title": "Activate plugin for this Page",
		"default_area": "navbar"
	},
	"background": { "page": "background.html" },
	"web_accessible_resources": [ "vendor/*", "js/*" ]
}
```
background.html
```html
<!DOCTYPE html>
<html lang='en'>
	<head>
		<meta charset='utf-8'>
	</head>
	<body>
		<script src='./vendor/webextension-polyfill/browser-polyfill.js'></script>
		<script async type='module' src='./vendor/es-module-shims/es-module-shims.wasm.js'></script>
		<script type='importmap'>
			{
				"imports": {
					"preact": "./vendor/preact/preact.module.js",
					"preact/jsx-runtime": "./vendor/preact/jsx-runtime/jsxRuntime.module.js",
					"preact/hooks": "./vendor/preact/hooks/hooks.module.js"
				}
			}
		</script>
		<script type='module' src='./js/background.js'></script>
	</body>
</html>
```

**Comment by MicahZoltu** [comment]
Firefox error:
> Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

**Comment by MicahZoltu** [comment]
Repro case: https://github.com/MicahZoltu/esm-extension/tree/es-module-shims-background-script-bug
1. Clone `es-module-shims-background-script-bug`
2. `npm install`
3. `npm run vendor`
4. `npm run build`
5. "Load unpacked" extension (Brave/Chrome) or "Load Temporary Add-On" (Firefox) and choose the `app` subdirectory of this project (Brave/Chrome) or `app/manifest.json` (Firefox).
6. Notice that you receive an error in the plugin page (Brave/Chrome) or when inspecting the plugin (Firefox).

You can remove the line `"background": { "page": "index.html" },` from `app/manifest.json` to make the problem go away, as this specifically is a CSP issue with the background page, not an issue with the pop-up page.

**Comment by MicahZoltu** [comment]
Hmm, it actually appears like I get the error in Brave, but the code actually executes despite that and modules are correctly loaded.  Firefox doesn't appear to work at all from what I can tell.

**Comment by guybedford** [comment]
@MicahZoltu could it be that the browser is running in polyfill mode but treating the import map as a script evaluation inline?

You likely have to switch to shim mode on 1.5.6 entirely. Did you try that?

**Comment by MicahZoltu** [comment]
Shim mode seems too work in brave, despite getting CSP errors.  Shim mode 1.5.6 doesn't appear to work in Firefox, and I don't see any errors (it just fails to execute anything).  0.6.0 works in Firefox with the exact same code.

**Comment by guybedford** [comment]
Was finally able to dig into this and post a fix in .

* The import map detection was not respecting the `HTMLScriptElement.supports('importmap') === false` case resulting in the iframe detection running, which was then not being supported in the extension environment as before
* The CSP policy in your manifest was missing `data:` URI support

There were some other subtle cases so I can see how it could be confusing - posted https://github.com/guybedford/es-module-shims/pull/302 which should fix it and help some of the debugging in future as well.

**Comment by guybedford** [comment]
Landed in 1.5.7.

**Comment by MicahZoltu** [comment]
I'm not an expert on CSP stuff, what do you mean by "missing `data:` URI support"?  How does one go about fixing that?

**Comment by MicahZoltu** [comment]
1.5.7 does appear to make things work in both Brave and Firefox, even without adding a `data:` item to the CSP stuff.  I still get a CSP error in Brave, but it appears I can just ignore that and everything works.
